'use_strict'

module.exports = {
    "ADD_MESSAGE": "Data successfully added!",
    "UPDATE_MESSAGE": "Data successfully updated!",
    "EXIST_ERROR": "A data already exists with this name",
    "DOES_NOT_EXIST": "Data does not exist",
    "WENT_WRONG": "Oops! Something went wrong",
    "DELETE_UNABLE": "Unable to delete the [ITEM]. Some [SUBITEM] may be associated with this [ITEM].",
    "DELETE_CONFIRMATION": "Successfully deleted",
    "STATUS_UPDATE": "Status update successfully!",
    "REGION_DUPLICATE": "A region already exists with this rank or name",
    "REGION_NOTEXSIST": "Region does not exist" ,
    "REGION_ADDSUCCESSFULLY": "Region added successfully!",
    "REGION_DELETED":"Region successfully deleted",
    "REGION_DELETE_ERROR":"Unable to delete the region. Some zones may be associated with this region.",
    "REGION_DELETE":"Unable to delete region",
    "COUNTRY_PARAMETER_MISMATCH":"Parameter Mismatch",
    "COUNTRY_ADDED_SUCCESSFULLY":"COUNTRY successfully added!",
    "COUNTRY_ADDED_ERROR":"Unable to delete the country. Some regions may be associated with this country.",
    "COUNTRY_DELETED_SUCCESSFULLY":"Country Deleted",
    "ZONE_PARAMETER_MISMATCH":"Parameter Mismatch",
    "ZONE_NOT_EXSIST":"Zone does not exist",
    "ZONE_ALLREADY_EXSIST":"A zone already exists with this rank or name",
    "ZONE_DELETE_UNABLE":"Unable to delete the zone. Some places may be associated with this place.",
    "ZONE_UPDATED":"zone successfully updated",
    "ZONE_ADDED":"New Zone Added",
    "ZONE_DELETED":"Zone Deleted Successfully",
    "PLACE_PARAMETER_MISMATCH":"Place Parameter Mismatched",
    "PLACE_DOESNOT_EXSIST":"Place Does Not Exsist",
    "PLACE_DELETED":"Place Deleted Successfully",
    "PLACE_ADDED":"Place Added Successfully",
    "PLACE_UPDATED":"Place Successfully Updated",
    "PLACE_DUPLICATE_EXSIST":"A place already exists with this rank or name",
    "TOUR_ADD":"Tour Added Successfuly",
    "TOUR_UPDATE":"Tour Updated Successfuly",
    "TOUR_ADD_FAILED":"Tour add failed",
    "TOUR_UPDATE_FAILED":"Tour Update Failed",
    "TOUR_PARAMS_MISMATCH":"Tour Parameter Mismatch",
    // For frontend
    "EXIST_USER": "User already exists with this email",
    "EMAIL_AVAILABLE": "This email is available",
    "SOMETHING_WENT_WRONG": "Something went wrong"
}